- 1.1.19
- _NAME: G305 Lightspeed Wireless Gaming Mouse
  _modelId: '407400000000'
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: EC848A2D
  _unitId: 512DCB67
  _wpid: '4074'
  dpi: 3000
  onboard_profiles: 1
  report_rate: 1
- _NAME: G305 Lightspeed Wireless Gaming Mouse
  _modelId: '407400000000'
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, report_rate: true}
  _serial: 95F02692
  _unitId: A51C12D7
  _wpid: '4074'
  dpi: 3200
  led_control: 0
  onboard_profiles: 1
  report_rate: 1
- _NAME: PRO X Wireless
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, scroll-ratchet-torque, smart-shift,
    thumb-scroll-invert, thumb-scroll-mode, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, force-sensing, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, haptic-level, haptic-play, sidetone, equalizer,
    adc_power_management]
  _battery: 4100
  _modelId: 4093C0940000
  _sensitive: {dpi: true, onboard_profiles: true}
  _serial: A7516020
  _unitId: A7516020
  _wpid: '4093'
  dpi: 400
  onboard_profiles: 257
  report_rate: 1
